import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import { ThemeProvider } from '../../contexts/ThemeContext/ThemeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Nabil's Blog",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <div data-theme='dark' className='max-w-[1440px] mx-auto main-div'>
            <Navbar />
            {children}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html >
  )
}
